apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-0 
  namespace: skillpulse
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi